#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+	listens on port 80.
#+	Returns a page containing "Hello world" when queried
#+	at the root with a curl GET request.
#+	configures /redirect me as a "301 moved permanently"
#+	Includes a custom 404 page containing "Ceci n'est pas une page".
#+	contains a custom HTTP header named X-Served-By.
#+	The value of the HTTP header is the hostname of the running server.

apt-get update
apt-get instal -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello world" > /var/www/html/index.html
touh /var/www/html/404.html
echo 'Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen[::]:80 default_server;
	add_header x-served-bt $HOSTNAME;
	root   /var/www/html;
	index index.html

	location /redirect_me {
		return 301 http://cuberule.com/;
	}

	error_page 404 /404.html;
	location /404
		root /var/www/
		internal;
	}
}" > etc/ngin/sites-available/default

servib again restart
}
