#!/usr/bin/env bash
# fix nginx listening on port 80
# Go to sites_enabled folder for Nginx
cd /etc/nginx/sites_enabled/ || exit;
# Delete the default file
rm default;
# Create symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restart
